-- SPDX-FileCopyrightText: 2026 Samuel Hulme <https://github.com/samuelh2005>
-- SPDX-License-Identifier: MPL-2.0

--[[ CC Web Browser v26

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at https://mozilla.org/MPL/2.0/.
--]]
local core = {}

core.logs = {}

core.checkVal = function(value, arg_type, default)
    if value == nil then
        return default, false, "Value is nil"
    end

    if arg_type and type(value) ~= arg_type then
        return default, false, "Expected type " .. arg_type .. ", got " .. type(value)
    end

    return value, true, nil
end

core.startsWith = function(str, prefix)
    return str:sub(1, #prefix) == prefix
end

core.stripPrefix = function(str, prefix)
    if core.startsWith(str, prefix) then
        return str:sub(#prefix + 1)
    end

    return str
end

core.consoleLog = function(status, msg)
    table.insert(
        core.logs,
        {
            ["status"] = status,
            ["message"] = msg
        }
    )
end

----------------------------------------------------------------
-- ContentFrame
--
-- A controllable text box.
--
-- The frame owns:
--   * contentWindow
--   * source line objects
--   * wrapped contentLines
--   * scrolling state
--   * scrollbar state
--   * scroll event handling
--
-- It knows nothing about:
--   * HTTP
--   * files
--   * JSON
--   * documents
--   * logs
----------------------------------------------------------------

local ContentFrame = {}
ContentFrame.__index = ContentFrame

function ContentFrame.new(parentTerm, x, y, width, height)
    local self = setmetatable({}, ContentFrame)

    self.term = parentTerm

    self.x = x
    self.y = y
    self.width = width
    self.height = height

    self.contentWindow = window.create(parentTerm, x, y, width, height)

    -- Original line objects.
    --
    -- A line may contain any additional metadata required by
    -- whoever owns the content.
    --
    -- {
    --     text = "Hello",
    --     textColor = colors.black,
    --     backgroundColor = colors.white
    -- }
    self.lines = {}

    -- Wrapped lines generated by render().
    self.contentLines = {}

    self.scrollOffset = 0

    -- Scrollbar state.
    self.scrollbarVisible = false
    self.scrollbarTrackHeight = 0
    self.scrollbarThumbHeight = 0
    self.scrollbarThumbPos = 0

    self.draggingScrollbar = false
    self.dragGrabOffset = 0

    return self
end

----------------------------------------------------------------
-- Content
----------------------------------------------------------------

function ContentFrame:pushLine(line)
    assert(type(line) == "table", "ContentFrame:pushLine expects a line object")

    assert(type(line.text) == "string", "ContentFrame line requires a text field")

    table.insert(self.lines, line)
end

function ContentFrame:clearLines()
    self.lines = {}
    self.contentLines = {}
    self.scrollOffset = 0

    self.draggingScrollbar = false
    self.dragGrabOffset = 0
end

----------------------------------------------------------------
-- Wrapping
----------------------------------------------------------------

function ContentFrame:wrapText(text, width)
    local lines = {}
    local currentLine = ""
    local currentWidth = 0

    for word in text:gmatch("%S+") do
        local wordWidth = #word

        if currentWidth + wordWidth + 1 > width then
            if currentLine ~= "" then
                table.insert(lines, currentLine)
            end

            currentLine = word .. " "
            currentWidth = wordWidth + 1
        else
            currentLine = currentLine .. word .. " "
            currentWidth = currentWidth + wordWidth + 1
        end
    end

    if currentLine ~= "" then
        table.insert(lines, currentLine)
    end

    return lines
end

function ContentFrame:buildContentLines()
    local lines = {}

    for _, line in ipairs(self.lines) do
        local wrapped = self:wrapText(line.text, self.width)

        for _, text in ipairs(wrapped) do
            table.insert(
                lines,
                {
                    text = text,
                    -- Copy presentation information from the source
                    -- line while retaining the original object.
                    textColor = line.textColor or colors.black,
                    backgroundColor = line.backgroundColor or colors.white,
                    source = line
                }
            )
        end
    end

    return lines
end

----------------------------------------------------------------
-- Scrolling
----------------------------------------------------------------

function ContentFrame:maxScroll()
    return math.max(0, #self.contentLines - self.height)
end

function ContentFrame:clampScroll()
    local max = self:maxScroll()

    if self.scrollOffset < 0 then
        self.scrollOffset = 0
    elseif self.scrollOffset > max then
        self.scrollOffset = max
    end
end

function ContentFrame:refreshContentLines()
    self.contentLines = self:buildContentLines()
    self:clampScroll()
end

function ContentFrame:scrollBy(amount)
    -- Wrapping is dependent on the current width, so make sure
    -- scrolling always operates against current contentLines.
    self:refreshContentLines()

    self.scrollOffset = self.scrollOffset + amount
    self:clampScroll()
end

function ContentFrame:scrollToTop()
    self:refreshContentLines()
    self.scrollOffset = 0
end

function ContentFrame:scrollToBottom()
    self:refreshContentLines()
    self.scrollOffset = self:maxScroll()
end

----------------------------------------------------------------
-- Sizing
----------------------------------------------------------------

function ContentFrame:setSize(width, height)
    self.width = width
    self.height = height

    self.contentWindow.reposition(self.x, self.y, width, height)

    self:refreshContentLines()
end

----------------------------------------------------------------
-- Rendering
----------------------------------------------------------------

function ContentFrame:renderScrollbar()
    local x = self.x + self.width
    local total = #self.contentLines
    local trackHeight = self.height

    self.scrollbarTrackHeight = trackHeight

    if total <= trackHeight then
        self.scrollbarVisible = false
        self.scrollbarThumbHeight = 0
        self.scrollbarThumbPos = 0

        self.term.setBackgroundColour(colors.white)

        for row = 0, trackHeight - 1 do
            self.term.setCursorPos(x, self.y + row)
            self.term.write(" ")
        end

        return
    end

    self.scrollbarVisible = true

    self.scrollbarThumbHeight = math.max(1, math.floor(trackHeight * trackHeight / total))

    local travel = trackHeight - self.scrollbarThumbHeight

    local max = self:maxScroll()

    self.scrollbarThumbPos = 0

    if max > 0 then
        self.scrollbarThumbPos = math.floor(travel * self.scrollOffset / max + 0.5)
    end

    for row = 0, trackHeight - 1 do
        self.term.setCursorPos(x, self.y + row)

        if row >= self.scrollbarThumbPos and row < self.scrollbarThumbPos + self.scrollbarThumbHeight then
            self.term.setBackgroundColour(colors.gray)
        else
            self.term.setBackgroundColour(colors.lightGray)
        end

        self.term.write(" ")
    end
end

function ContentFrame:render()
    -- Wrapping happens here, so a terminal resize automatically
    -- rebuilds the wrapped representation from the original lines.
    self:refreshContentLines()

    self.contentWindow.setBackgroundColour(colors.white)

    self.contentWindow.setTextColour(colors.black)

    self.contentWindow.setCursorPos(1, 1)
    self.contentWindow.clear()

    for row = 1, self.height do
        local line = self.contentLines[row + self.scrollOffset]

        if line then
            self.contentWindow.setBackgroundColour(line.backgroundColor)

            self.contentWindow.setTextColour(line.textColor)

            self.contentWindow.setCursorPos(1, row)

            self.contentWindow.clearLine()
            self.contentWindow.write(line.text)
        end
    end

    self:renderScrollbar()
end

----------------------------------------------------------------
-- Event handling
----------------------------------------------------------------

function ContentFrame:handleEvent(event, p1, p2, p3)
    if event == "mouse_click" and p1 == 1 then
        local mouseX = p2
        local mouseY = p3

        local scrollbarX = self.x + self.width

        if
            self.scrollbarVisible and mouseX == scrollbarX and mouseY >= self.y and
                mouseY < self.y + self.scrollbarTrackHeight
         then
            self:refreshContentLines()

            local row = mouseY - self.y

            -- Clicked the scrollbar thumb.
            if row >= self.scrollbarThumbPos and row < self.scrollbarThumbPos + self.scrollbarThumbHeight then
                -- Clicked the scrollbar track.
                self.draggingScrollbar = true

                self.dragGrabOffset = row - self.scrollbarThumbPos
            else
                local travel = self.scrollbarTrackHeight - self.scrollbarThumbHeight

                local target = row - math.floor(self.scrollbarThumbHeight / 2)

                if travel > 0 then
                    self.scrollOffset = math.floor(self:maxScroll() * target / travel + 0.5)

                    self:clampScroll()
                end
            end

            return true
        end
    elseif event == "mouse_drag" and p1 == 1 and self.draggingScrollbar then
        self:refreshContentLines()

        local travel = self.scrollbarTrackHeight - self.scrollbarThumbHeight

        if travel > 0 then
            local row = p3 - self.y - self.dragGrabOffset

            self.scrollOffset = math.floor(self:maxScroll() * row / travel + 0.5)

            self:clampScroll()
        end

        return true
    elseif event == "mouse_up" then
        self.draggingScrollbar = false
        return true
    elseif event == "mouse_scroll" then
        self:scrollBy(p1 * 3)
        return true
    elseif event == "key" then
        if p1 == keys.down then
            self:scrollBy(1)
        elseif p1 == keys.up then
            self:scrollBy(-1)
        elseif p1 == keys.pageDown then
            self:scrollBy(self.height)
        elseif p1 == keys.pageUp then
            self:scrollBy(-self.height)
        elseif p1 == keys.home then
            self:scrollToTop()
        elseif p1 == keys["end"] then
            self:scrollToBottom()
        else
            return false
        end

        return true
    elseif event == "term_resize" then
        local width, height = self.term.getSize()

        self:setSize(width - 1, height - 2)

        return true
    end

    return false
end

----------------------------------------------------------------
-- Browser state
----------------------------------------------------------------

local defaultTheme = {
    ["body"] = {
        ["text-color"] = "black",
        ["background-color"] = "white"
    }
}

local w, h = term.getSize()
local currentTheme = defaultTheme

local url = "about:blank"
local loading = false

local contentFrame = ContentFrame.new(term.current(), 1, 2, w - 1, h - 2)

----------------------------------------------------------------
-- Browser content
--
-- These functions translate application data into line objects.
-- ContentFrame itself remains unaware of what those lines mean.
----------------------------------------------------------------

local function displayLogs()
    contentFrame:clearLines()

    for _, err in ipairs(core.logs) do
        contentFrame:pushLine(
            {
                text = "[" .. err.status .. "]: " .. err.message,
                textColor = colors.red,
                backgroundColor = colors.white
            }
        )
    end

    contentFrame:scrollToTop()
end

----------------------------------------------------------------
-- Page parsing
----------------------------------------------------------------

local function displayPage(content)
    if not content then
        core.consoleLog("error", "No content to display")
        return false
    end

    local json, err = textutils.unserialiseJSON(content)

    if not json then
        core.consoleLog("error", "Failed to parse JSON: " .. err)
        return false
    end

    local body, ok, bodyErr = core.checkVal(json["body"], "table", {})

    if not ok then
        core.consoleLog("error", "Failed to check body: " .. bodyErr)
        return false
    end

    -- The parsed document does not need to be stored anywhere.
    -- Its elements are translated straight into ContentFrame
    -- line objects.
    contentFrame:clearLines()

    for _, element in ipairs(body) do
        local elementType, typeOK, typeErr = core.checkVal(element["type"], "string", nil)

        if not typeOK then
            core.consoleLog("error", "Failed to check element type: " .. typeErr)
        elseif elementType == "text" then
            local text, textOK, textErr = core.checkVal(element["text"], "string", "")

            if not textOK then
                core.consoleLog("error", "Failed to check text element: " .. textErr)
            else
                contentFrame:pushLine(
                    {
                        text = text,
                        textColor = colors.black,
                        backgroundColor = colors.white
                    }
                )
            end
        end
    end

    contentFrame:scrollToTop()

    return true
end

----------------------------------------------------------------
-- URL editor
----------------------------------------------------------------

local function editValue(currentValue, prompt)
    local dialogW = math.min(30, w - 4)

    local dialogH = 5

    local x = math.floor((w - dialogW) / 2) + 1

    local y = math.floor((h - dialogH) / 2) + 1

    term.setBackgroundColour(colors.gray)
    term.setTextColour(colors.white)

    for row = 0, dialogH - 1 do
        term.setCursorPos(x, y + row)

        term.write(string.rep(" ", dialogW))
    end

    term.setCursorPos(x + 2, y + 1)

    term.write(prompt)

    term.setCursorPos(x + 2, y + 2)

    local newValue = read()

    if newValue ~= "" then
        return newValue
    end

    return currentValue
end

----------------------------------------------------------------
-- GET
----------------------------------------------------------------

local function GET(sourceUrl)
    if core.startsWith(sourceUrl, "file://") then
        local fileName = shell.resolve(core.stripPrefix(sourceUrl, "file://"))

        if not fs.exists(fileName) then
            core.consoleLog("error", "File not found: " .. fileName)
            return false
        end

        local file = fs.open(fileName, "r")

        if not file then
            core.consoleLog("error", "Failed to open file: " .. fileName)
            return false
        end

        local content = file.readAll()

        file.close()

        if not content or #content == 0 then
            core.consoleLog("error", "File is empty: " .. fileName)
            return false
        end

        return true, {
            content = content
        }
    elseif core.startsWith(sourceUrl, "http://") or core.startsWith(sourceUrl, "https://") then
        local request = http.get(sourceUrl)

        if not request then
            core.consoleLog("error", "Failed to make HTTP request to: " .. sourceUrl)
            return false
        end

        local statusCode = request.getResponseCode()

        local headers = request.getResponseHeaders()

        local content = request.readAll()

        request.close()

        if statusCode ~= 200 then
            if not content then
                core.consoleLog("error", "HTTP request failed with status code: " .. statusCode)
            else
                core.consoleLog("error", content)
            end
            return false
        end

        if not content or #content == 0 then
            core.consoleLog("error", "HTTP response is empty for: " .. sourceUrl)
            return false
        end

        return true, {
            content = content,
            statusCode = statusCode,
            headers = headers
        }
    end

    core.consoleLog("error", "Unsupported URL scheme: " .. sourceUrl .. " Supported schemes are file://, http://, and https://")
    return false
end

----------------------------------------------------------------
-- Browser chrome
----------------------------------------------------------------

local function fillLine(y, bg, fg, text)
    term.setBackgroundColour(bg)
    term.setTextColour(fg)

    term.setCursorPos(1, y)

    term.clearLine()

    if text then
        term.write(text)
    end
end

local function renderChrome()
    term.setBackgroundColour(colors.white)
    term.setTextColour(colors.black)
    term.clear()

    ------------------------------------------------------------
    -- Header
    ------------------------------------------------------------

    fillLine(1, colors.lightGray, colors.black)

    term.setBackgroundColour(colors.gray)
    term.setTextColour(colors.white)

    term.setCursorPos(2, 1)

    term.write(url)

    ------------------------------------------------------------
    -- Footer
    ------------------------------------------------------------

    local status = "Ready"

    if loading then
        status = "Loading..."
    elseif #core.logs > 0 then
        status = "Error"
    end

    fillLine(h, colors.lightGray, colors.black, status)
end

renderChrome()
contentFrame:render()

while true do
    local event, p1, p2, p3, p4, p5 = os.pullEvent()

    ------------------------------------------------------------
    -- Give ContentFrame first chance to consume the event.
    --
    -- This covers:
    --   mouse wheel
    --   scrollbar clicks
    --   scrollbar dragging
    --   keyboard scrolling
    --   terminal resize
    ------------------------------------------------------------

    local handled = contentFrame:handleEvent(event, p1, p2, p3)

    if not handled then
        --------------------------------------------------------
        -- URL bar
        --------------------------------------------------------

        if event == "mouse_click" and p1 == 1 then
            if p3 == 1 and p2 >= 2 and p2 <= #url + 1 then
                url = editValue(url, "Enter URL:")

                core.logs = {}

                contentFrame:clearLines()

                loading = true

                renderChrome()
                contentFrame:render()

                local ok, response = GET(url)
                loading = false

                if ok and response then
                    displayPage(response.content)
                end

                if #core.logs > 0 then
                    displayLogs()
                end
            end
        elseif event == "terminate" then
            break
        end
    end

    renderChrome()
    contentFrame:render()
end
